# Generated by Django 5.0.6 on 2024-06-08 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0004_group_related_terms"),
        ("groupleader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "library_type",
                    models.CharField(
                        choices=[("AI", "AI Library"), ("FILES", "Files Library")],
                        max_length=10,
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="group.group"
                    ),
                ),
            ],
        ),
    ]
