# Generated by Django 5.0.6 on 2024-06-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groupleader", "0003_libraryfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryfile",
            name="is_synchronize",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="libraryoption",
            name="library_type",
            field=models.CharField(
                choices=[("AI", "AI "), ("FILES", "FILES")], default="AI", max_length=10
            ),
        ),
    ]
