# Generated by Django 5.0.6 on 2024-06-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groupleader", "0003_libraryfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="libraryoption",
            name="library_type",
            field=models.CharField(
                choices=[("AI", "AI "), ("FILES", "FILES")], default="AI", max_length=10
            ),
        ),
    ]
