# Generated by Django 5.0.6 on 2024-10-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0005_group_related_terms_library_b"),
        ("groupleader", "0005_libraryfile_is_synchronize"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="libraryfile",
            name="group",
        ),
        migrations.AddField(
            model_name="libraryfile",
            name="group",
            field=models.ManyToManyField(
                related_name="library_files", to="group.group"
            ),
        ),
    ]
