# Generated by Django 4.1.7 on 2024-02-22 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0003_usergroup_unique_user_per_group"),
        ("in_app_chat", "0002_inappchat_unique_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inappchat",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_chats",
                to="group.group",
            ),
        ),
    ]
