# Generated by Django 4.1.7 on 2024-03-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("in_app_chat", "0003_alter_inappchat_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="inappchat",
            name="content_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
