# Generated by Django 5.0.4 on 2024-05-03 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("in_app_chat", "0005_inappchat_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inappchat",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
