# Generated by Django 5.0.6 on 2024-09-28 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("in_app_chat", "0006_alter_inappchat_score"),
        ("resource", "0008_resourcedownload"),
    ]

    operations = [
        migrations.AddField(
            model_name="inappchat",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inappchat_resource",
                to="resource.resources",
            ),
        ),
    ]
