# Generated by Django 5.0.6 on 2024-06-20 17:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity_flag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type_id",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Blog"), (3, "Forum"), (4, "Browser"), (2, "Chat")]
                    ),
                ),
                ("flagged_id", models.PositiveIntegerField()),
                ("description", models.TextField()),
                (
                    "datetime_flagged",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "flagged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("activity_type_id", "flagged_by", "flagged_id")},
            },
        ),
    ]
