# Generated by Django 5.0.6 on 2024-06-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_flag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity_flag",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="activity_flag",
            name="flag_count",
            field=models.IntegerField(default=0),
        ),
    ]
