# Generated by Django 5.0.6 on 2024-06-24 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_flag", "0002_activity_flag_active_activity_flag_flag_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity_flag",
            old_name="flagged_id",
            new_name="activity_id",
        ),
        migrations.RenameField(
            model_name="activity_flag",
            old_name="description",
            new_name="comment",
        ),
        migrations.AlterUniqueTogether(
            name="activity_flag",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="activity_flag",
            name="author_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity_flag",
            name="group_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="activity_flag",
            name="flagged_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flagged_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activity_flag",
            unique_together={("activity_type_id", "flagged_by", "activity_id")},
        ),
    ]
