# Generated by Django 5.0.6 on 2024-06-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_flag", "0003_rename_flagged_id_activity_flag_activity_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity_flag",
            name="author_id",
            field=models.PositiveIntegerField(),
        ),
    ]
