# Generated by Django 4.1.7 on 2024-01-03 12:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resource", "0002_alter_resources_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="media",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="media"
            ),
        ),
    ]
