# Generated by Django 4.1.7 on 2024-01-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource", "0003_resources_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resources",
            name="media",
        ),
        migrations.AddField(
            model_name="resources",
            name="cloud_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="resources",
            name="media_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
