# Generated by Django 4.1.7 on 2024-01-08 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0001_initial"),
        ("group", "0001_initial"),
        ("platforms", "0001_initial"),
        ("resource", "0004_remove_resources_media_resources_cloud_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resources",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="group_resources",
                to="group.group",
            ),
        ),
        migrations.AlterField(
            model_name="resources",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="organization_resources",
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="resources",
            name="platform",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="platform_resources",
                to="platforms.platform",
            ),
        ),
        migrations.AlterField(
            model_name="resources",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver_resources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="resources",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_resources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
