# Generated by Django 4.1.7 on 2024-03-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resource",
            "0005_alter_resources_group_alter_resources_organization_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="resources",
            name="type",
            field=models.CharField(
                choices=[
                    ("AUDIO", "AUDIO"),
                    ("VIDEO", "VIDEO"),
                    ("IMAGE", "IMAGE"),
                    ("DOCUMENT", "DOCUMENT"),
                    ("OTHERS", "OTHERS"),
                ],
                default="IMAGE",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Type",
        ),
    ]
