# Generated by Django 5.0.6 on 2024-06-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource", "0006_alter_resources_type_delete_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceFileSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("AUDIO", "AUDIO"),
                            ("VIDEO", "VIDEO"),
                            ("IMAGE", "IMAGE"),
                            ("DOCUMENT", "DOCUMENT"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("max_size", models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
