# Generated by Django 4.1.7 on 2024-01-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0002_usergroup"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="usergroup",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_user_per_group"
            ),
        ),
    ]
