# Generated by Django 5.0.6 on 2024-06-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0004_group_related_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="related_terms_library_b",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
