# Generated by Django 4.1.7 on 2024-02-16 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("group", "0003_usergroup_unique_user_per_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0002_alter_organization_organization_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "recipent_type",
                    models.CharField(
                        choices=[
                            ("ORGANIZATION", "ORGANIZATION"),
                            ("GROUP", "GROUP"),
                            ("PLATFORM", "PLATFORM"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "concerned_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_feedbbacks",
                        to="group.group",
                    ),
                ),
                (
                    "concerned_organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_feedbacks",
                        to="organization.organization",
                    ),
                ),
                (
                    "concerned_platform",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_feedbbacks",
                        to="group.group",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
