# Generated by Django 5.0.4 on 2024-05-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="is_sorted",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
