# Generated by Django 5.0.6 on 2024-06-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_feedback_is_sorted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="recipent_type",
            field=models.CharField(
                choices=[
                    ("ORGANIZATION", "ORGANIZATION"),
                    ("GROUP", "GROUP"),
                    ("PLATFORM", "PLATFORM"),
                ],
                default="ORGANIZATION",
                max_length=20,
            ),
        ),
    ]
