# Generated by Django 4.1.7 on 2024-01-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_forum_temp_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forum",
            name="category",
        ),
    ]
