# Generated by Django 4.1.7 on 2024-01-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_remove_forum_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forum",
            old_name="temp_category",
            new_name="category",
        ),
    ]
