# Generated by Django 4.1.7 on 2024-02-10 07:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_alter_organization_organization_id_and_more"),
        ("group", "0003_usergroup_unique_user_per_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0005_comment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="ForumComment",
        ),
    ]
