# Generated by Django 4.1.7 on 2024-03-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource", "0006_alter_resources_type_delete_type"),
        ("forum", "0006_rename_comment_forumcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="resources",
            field=models.ManyToManyField(
                related_name="forums", to="resource.resources"
            ),
        ),
    ]
