# Generated by Django 4.1.7 on 2024-03-25 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0008_commentreplies"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="forum",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="commentreplies",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_replies",
                to="forum.forumcomment",
            ),
        ),
    ]
