# Generated by Django 5.0.4 on 2024-05-03 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0009_forum_end_time_forum_start_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentreplies",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=2,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="forum",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=2,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="forumcomment",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=2,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
