# Generated by Django 4.0.4 on 2023-11-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groupId',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='roleId',
            field=models.SmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
