# Generated by Django 4.0.4 on 2023-11-27 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_groupid_user_roleid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='groupId',
            new_name='groupI_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='roleId',
            new_name='role_id',
        ),
    ]
