# Generated by Django 4.0.4 on 2023-11-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_groupid_user_groupi_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groupI_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.IntegerField(),
        ),
    ]
