# Generated by Django 4.0.4 on 2023-11-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_groupi_id_alter_user_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='groupI_id',
            new_name='group_id',
        ),
    ]
