# Generated by Django 4.1.7 on 2023-12-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_groupi_id_user_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_id",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
