# Generated by Django 4.1.7 on 2023-12-04 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_is_verified_user_organization_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=255, null=True)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("ACCOUNT_VERIFICATION", "ACCOUNT_VERIFICATION"),
                            ("PASSWORD_RESET", "PASSWORD_RESET"),
                        ],
                        default="ACCOUNT_VERIFICATION",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
