# Generated by Django 4.1.7 on 2023-12-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization_id",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
