# Generated by Django 4.1.7 on 2023-12-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_user_email_alter_user_group_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="group_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="role_id",
            field=models.IntegerField(),
        ),
    ]
