# Generated by Django 4.1.7 on 2023-12-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0011_user_created_at_user_updated_at_alter_user_group_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="group_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=45, null=True),
        ),
    ]
