# Generated by Django 4.1.7 on 2024-01-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_user_options_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "MALE"), ("FEMALE", "FEMALE")],
                max_length=20,
                null=True,
            ),
        ),
    ]
