# Generated by Django 4.1.7 on 2024-01-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cloud_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="image_url",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=17, null=True),
        ),
    ]
