# Generated by Django 4.1.7 on 2024-01-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_user_cloud_id_user_image_url_alter_user_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="group_id",
        ),
    ]
