# Generated by Django 4.1.7 on 2024-01-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_user_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="temp_group_id",
            field=models.IntegerField(null=True),
        ),
    ]
