# Generated by Django 4.1.7 on 2024-01-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_user_temp_group_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="temp_group_id",
            new_name="first_group_id",
        ),
    ]
