# Generated by Django 4.1.7 on 2024-03-24 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_rename_temp_group_id_user_first_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="online_count",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
