# Generated by Django 5.0.6 on 2024-09-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_user_online_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
    ]
