# Generated by Django 4.1.7 on 2024-01-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource", "0004_remove_resources_media_resources_cloud_id_and_more"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="resources",
            field=models.ManyToManyField(
                null=True, related_name="blogs", to="resource.resources"
            ),
        ),
    ]
