# Generated by Django 4.1.7 on 2024-01-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_new_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="category",
        ),
    ]
