# Generated by Django 4.1.7 on 2024-01-15 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("blog", "0002_blog_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="temp_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cat_blogs",
                to="category.category",
            ),
        ),
    ]
