# Generated by Django 4.1.7 on 2024-01-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_blog_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="new_key",
            new_name="category",
        ),
    ]
