# Generated by Django 4.1.7 on 2024-01-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resource",
            "0005_alter_resources_group_alter_resources_organization_and_more",
        ),
        ("blog", "0004_rename_new_key_blog_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="resources",
            field=models.ManyToManyField(related_name="blogs", to="resource.resources"),
        ),
    ]
