# Generated by Django 4.1.7 on 2024-03-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_blogcommentreplies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="Platform",
            new_name="platform",
        ),
    ]
