# Generated by Django 5.0.4 on 2024-05-03 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_remove_comment_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=2,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="blogcommentreplies",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=2,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=2,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
