# Generated by Django 5.0.4 on 2024-05-03 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_blog_score_blogcommentreplies_score_comment_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="blogcommentreplies",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
