# Generated by Django 4.1.7 on 2024-01-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("group", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Socialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_blog", models.IntegerField(default=0)),
                ("send_chat_message", models.IntegerField(default=0)),
                ("post_forum", models.IntegerField(default=0)),
                ("image_sharing", models.IntegerField(default=0)),
                ("video_sharing", models.IntegerField(default=0)),
                ("text_resource_sharing", models.IntegerField(default=0)),
                ("created_topic", models.IntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_socs",
                        to="group.group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="organization_socs",
                        to="organization.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Internalization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_in_app_browser", models.IntegerField(default=0)),
                ("read_blog", models.IntegerField(default=0)),
                ("read_forum", models.IntegerField(default=0)),
                ("recieve_chat_message", models.IntegerField(default=0)),
                ("download_resources", models.IntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_inters",
                        to="group.group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="organization_inters",
                        to="organization.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Externalization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_blog", models.IntegerField(default=0)),
                ("send_chat_message", models.IntegerField(default=0)),
                ("post_forum", models.IntegerField(default=0)),
                ("created_topic", models.IntegerField(default=0)),
                ("comment", models.IntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_exts",
                        to="group.group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="organization_exts",
                        to="organization.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Combination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_topic", models.IntegerField(default=0)),
                ("post_blog", models.IntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_combs",
                        to="group.group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="organization_combs",
                        to="organization.organization",
                    ),
                ),
            ],
        ),
    ]
