# Generated by Django 4.1.7 on 2024-01-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        ("group", "0001_initial"),
        ("leader", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="combination",
            unique_together={("organization", "group")},
        ),
        migrations.AlterUniqueTogether(
            name="externalization",
            unique_together={("organization", "group")},
        ),
        migrations.AlterUniqueTogether(
            name="internalization",
            unique_together={("organization", "group")},
        ),
        migrations.AlterUniqueTogether(
            name="socialization",
            unique_together={("organization", "group")},
        ),
    ]
