# Generated by Django 5.0.6 on 2024-09-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_log", "0002_alter_activitylog_action_user_alter_activitylog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login_success", "Login Successful"),
                    ("login_failed_unverified", "Login Failed Unverified"),
                    ("login_failed_credentials", "Login Failed Credentials"),
                    ("reset_password", "Reset Password"),
                    ("changed_password", "Changed Password"),
                    ("logout", "Logout"),
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                ],
                max_length=50,
            ),
        ),
    ]
