# Generated by Django 5.0.6 on 2024-10-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("browser_history", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="browserhistory",
            old_name="end_time",
            new_name="browse_end_time",
        ),
        migrations.RenameField(
            model_name="browserhistory",
            old_name="start_time",
            new_name="browse_start_time",
        ),
    ]
