# Generated by Django 5.0.6 on 2024-10-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "browser_history",
            "0002_rename_end_time_browserhistory_browse_end_time_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="browserhistory",
            old_name="browse_end_time",
            new_name="end_time",
        ),
        migrations.RenameField(
            model_name="browserhistory",
            old_name="browse_start_time",
            new_name="start_time",
        ),
    ]
